### PR TITLE
[Enhancement] Git branch as argument

### PR DESCRIPTION
**Pull request by truenorth**
Although most of the time people will want to push to the `gh-pages` branch, there's a certain case where you want to push your "dist" app to master: the `<username>.github.io` case. 

From Github docs: [User, Organization pages](https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages)

> Content from the master branch will be used to build and publish your GitHub Pages site.

#### Example Usage

```sh
git checkout master
ember github-pages:commit --message "Initial demo app release" \
                          --branch master \
                          --environment development
```

### CODE REVIEW

**Comment by truenorth** [comment]
Hey guys, I'm sure you're busy, but could you take a look at this and #20? I'm going to give a talk that refers to this add-on, and if possible I'd like to avoid needing to tell people they have to use my branch

**Comment by DanielOchoa** [comment]
I'll publish it sometime later today.

**Comment by truenorth** [comment]
Awesome! thanks @DanielOchoa

**Comment by DanielOchoa** [comment]
this is an awesome commit btw

**Comment by DanielOchoa** [comment]
it has now been published.

**Pull request merged**
