### PR TITLE
Fix grep command to correctly exclude . and ..

### PR DESCRIPTION
**Pull request by jessepinho**
Otherwise, I get the following error: `rm: "." and ".." may not be removed`.

### CODE REVIEW

**Comment by jhr007** [comment]
I had the same issue with ` . `and ` .. `
Also for me, it didn't commit the deleted files, `git add .` should be `git add -u`
git version `1.7.10.4`

**Comment by osxi** [comment]
@jhr007: that's a good point about updating the index.

@jessepinho, can you please go ahead and change the `git add .` to read `git add -u .` and squash into your current commit?

**Comment by jhr007** [comment]
@jessepinho @osxi 
The `gh-pages` branch is actually empty here. 

I actually think `git add .` is required. Maybe even `git add -a`

I'm not sure what problem I was having with deleted files.

**Comment by osxi** [comment]
`git add .` and `git add -u .` worked for me on random projects.

If we want to cover all bases, let's use `git add -A`, which is the equivalent of doing `git add .` followed by `git add -u`.

**Comment by jessepinho** [comment]
@jhr007 @osxi I added the change. Please review and confirm, and I can then squash the commit.

**Comment by osxi** [comment]
@jessepinho Thanks!

**Pull request merged**
